{"name": "Проверяем вход в аккаунт курьера с несуществующим логином", "status": "passed", "start": 1739629512467, "stop": 1739629512844, "uuid": "dc40af55-5d35-461d-aaa7-5b773967f997", "historyId": "ac05f8f2b041f62c7727b84aa71195ae", "testCaseId": "ac05f8f2b041f62c7727b84aa71195ae", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-UNQET23V"}, {"name": "thread", "value": "29468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}